# Generated by Django 5.2.7 on 2025-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('En reparacion', 'En reparacion'), ('Dado de baja', 'Dado de baja')], default='Operativo', max_length=50),
        ),
    ]
